name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Build and run tests
    - run: npm ci
    - run: npm run build
    - run: npm run test
