name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Needed by build_changelog step to get all available tags, not only the latest

      # Init npm
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set git username and email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      # Build and run tests
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:components
      - run: npm run build --if-present
      - run: npm run test:e2e

      # Build Changelog
#      - name: Build Changelog
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          configuration: ".github/config/changelog.json"

      # Bump version, generate CHANGELOG.md, tag and push new commit
      - run: npm run release

      # Used for the release
      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | xargs)
          echo "::set-output name=TAG::v$VERSION"

      # Used for the release
#      - name: Get changelog
#        uses: actions/github-script@v5
#        id: get_changelog
#        with:
#          script: |
#            return require('./scripts/get-changelog.js')({github, context});
#          result-encoding: string

      # Used for the release
#      - name: Get changelog #2
#        id: get_changelog
#        run: |
#          CHANGELOG="$(node ./scripts/get-changelog.js)"
#          CHANGELOG="${CHANGELOG//'%'/'%25'}"
#          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
#          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
#          echo "::set-output name=CHANGELOG::${CHANGELOG}"

      - name: Get changelog #2
        id: get_changelog
        run: node ./scripts/ci/standard-version/updater/changelog-parser.js

      # Create release
      - name: Create release including build files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./dist/animated-greetings.zip
          tag: "${{steps.get_version.outputs.TAG}}"
          release_name: "${{steps.get_version.outputs.TAG}}"
          overwrite: true
#          body: "${{ steps.get_changelog.outputs.result}}"
          body: "${{ steps.get_changelog.outputs.release}}"
