# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

      # This step reads a file from repo and use it for body of the release
      # This works on any self-hosted runner OS
    - name: Parse version from package.json
      id: read_version
      shell: bash
      run: |
        VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | xargs)
        echo "::set-output name=VERSION::$VERSION"

    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: ".github/config/changelog.json"

    - name: Create release including build files
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ./dist/animated-greetings.zip
        tag: "v${{steps.read_version.outputs.VERSION}}"
        release_name: "v${{steps.read_version.outputs.VERSION}}"
        overwrite: true
        body: "${{steps.build_changelog.outputs.changelog}}"

## TODO: Create a "Release vX.X.X" PR on tag push,