name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Init npm
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      # Used for the version bump/changelog commit
      - name: Set git username and email
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      # Build and run tests
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run docgen
      - run: npm run release

      - name: Get version
        id: get_version
        run: npx ts-node ./scripts/ci/get-version.ts

      - name: Get changelog
        id: get_changelog
        run: npx ts-node ./scripts/ci/get-changelog.ts

      # Create release
      - name: Create release including build files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./dist/animated-greetings.zip
          tag: "${{steps.get_version.outputs.tag}}"
          release_name: "${{steps.get_version.outputs.tag}}"
          overwrite: true
          body: "${{ steps.get_changelog.outputs.body}}"
