name: Release

on:
  workflow_dispatch:
    inputs:
      testinput:
        description: 'A test input'
        required: true
        default: 'default value'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Needed by build_changelog step to get all available tags, not only the latest

      # Init npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Parse version
      - name: Parse version from package.json
        id: read_version
        shell: bash
        run: |
          VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | xargs)
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=TAG::v$VERSION"

        # Install deps and build project

      - run: npm run test:unit
      - run: npm run test:components
      - run: npm run build --if-present
      - run: npm run test:e2e

      # Bump version, generate CHANGELOG.md, tag and push new commit
      - run: npm run release

      # Build Changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/config/changelog.json"

      # Create release
      - name: Create release including build files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./dist/animated-greetings.zip
          tag: "${{steps.read_version.outputs.TAG}}"
          release_name: "${{steps.read_version.outputs.TAG}}"
          overwrite: true
          body: "${{steps.build_changelog.outputs.changelog}}"